### ISSUE TITLE
Ingredients of type ProcessedItem are spawned

### ISSUE THREAD

**Issue by mserquet** [TheJP/GlobalGameJam2018Alchemy#24]
Currently, Ingredients can be set of type ProcessedItem, and single-player mode may spawn such items.
But this item type should be reserved for the class ProcessedItem.

The Item-Handling may need some refactoring.

**Comment by TheJP** [comment]
I know what causes items of the wrong type to spawn in singleplayer. Going to fix that tomorrow

**Comment by TheJP** [comment]
Fixed as far as I see it. @Hackempluf please review if the bug is fixed or still occurring
