### ISSUE TITLE
Paste Ingredient

### ISSUE THREAD

**Issue by mserquet** [TheJP/GlobalGameJam2018Alchemy#25]
The Pipes game has another ingredient of type paste, but there is no matching Item-Type on the networking side and our side.

**Comment by TheJP** [comment]
I think that is on purpose. Maybe we should discuss it with @Dravere or @exa-soft

**Comment by Dravere** [comment]
Paste at the moment needs to be trashed. We introduced it because there was some talks going on that we might introduce paste at a later time. But at the moment this is just a mixture mistake the player can create and then has to trash.

**Comment by TheJP** [comment]
Thanks for the clarification. Then I'm going to close the issue for now. (Feel free to reopen)
